<?php

/**
 * Plugin Name: Exact Target Email Form
 * Plugin URI: http://www.riseproject.com/
 * Version: 1.0.1
 * Author: Vik Ewoods
 * Description: Widget for subscription form from Exact Target (SalesForce)
 **/

class Exact_Target_Widget extends WP_Widget
{

    public function __construct()
    {
        parent::__construct("exact_target_widget",
            __("Exact Target Widget", "exact_target_widget_domain"),
            array("description" => __("Widget for subscription form from Exact Target (SalesForce)", "exact_target_widget_domain"))
        );
    }

    public function widget($args, $instance)
    {
        parent::widget($args, $instance); // TODO: Change the autogenerated stub
    }

    public function form($instance)
    {
        return parent::form($instance); // TODO: Change the autogenerated stub
    }

    public function update($new_instance, $old_instance)
    {
        return parent::update($new_instance, $old_instance); // TODO: Change the autogenerated stub
    }

}


/*
 * Adding action to init widget
 */
function exact_target_load_widget()
{
    register_widget('exact_target_widget');
}

add_action('widgets_init', 'exact_target_load_widget');

?>
